steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'jib']
    id: 'Build image with Jib'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gradlespringbootsrv',
      '--image', 'gcr.io/suga-new01/gradlespringboot',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
    id: 'Deploy to Cloud Run'
images:
  - 'gcr.io/suga-new01/gradlespringboot'
