steps:
  # Step 1: Building the Docker image
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'install']

  # Step 2: Run tests with coverage and generate coverage reports
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['test', 'jacoco:report']