steps:
  # Step 1: Building the Docker image
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'gradle'
    args: ['test']

  # Step 2: SonarCloud analysis
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'sh'
    args: [
      '-c',
      'gradle test jacocoTestReport sonarqube \
       -Dsonar.projectKey=gradlespringboot \
       -Dsonar.organization=suganandan \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.login=$SONARCLOUD_TOKEN'
    ]
    env:
      - 'SONARCLOUD_TOKEN=d6ce8689c7a01c4d897188425e5f21896f2e33ca'
      
  # Step 2: Building and pushing Docker image with Jib
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build', 'jib']

  # Step 4: Deploying to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gcpservice1'
      - '--image=gcr.io/suga-new01/gradleservice:01'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'  # Adjust as per your authentication needs