steps:
  # Step 1: Install Java 17
  - name: 'gcr.io/cloud-builders/bazel'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y openjdk-17-jdk && \
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 && \
        ./gradlew clean build

  # Step 2: Build and push the Docker image using Jib
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['./gradlew', 'jib', '--image=gcr.io/$PROJECT_ID/my-spring-boot-app']
    env:
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'my-spring-boot-app', '--image', 'gcr.io/$PROJECT_ID/my-spring-boot-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/my-spring-boot-app'
