steps:
  # Step 1: Build the project with Gradle
  - name: 'gradle:7.4-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build', '--no-daemon']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gradlespringboot/gradlespringboot:$SHORT_SHA', '.']

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gradlespringboot/gradlespringboot:$SHORT_SHA']

# Substitutions
substitutions:
  _GITHUB_USERNAME: 'suganandan'
  _REPOSITORY_NAME: 'gradlespringboot'
  _BRANCH_NAME: 'main' # or whatever branch you want to use
  _SERVICE_NAME: 'gradlespringboot'
  _VERSION: '0.0.1-SNAPSHOT' # or dynamic versioning

# Timeouts and other options
timeout: '900s'
