steps:
  # Step 1: Building the Docker image
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build','jib']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/suga-new01/gradleservice:01' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gradleservice'
      - '--image'
      - 'gcr.io/suga-new01/gradleservice:01'
      - '--region'
      - 'us-central1'
  images:
    - 'gcr.io/suga-new01/gradleservice:01'