steps:
  # Step 1: Building the Docker image
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build','test', 'jacoco:report','sonarqube','jib']

  # Step 4: Deploying to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gcpservice'
      - '--image=gcr.io/suga-new01/gradleservice:01'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'  # Adjust as per your authentication needs