steps:
  # Step 1: Build the project with Gradle
  - name: 'gradle:8.5-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build', '--no-daemon']

# Substitutions
substitutions:
  _GITHUB_USERNAME: 'suganandan'
  _REPOSITORY_NAME: 'gradlespringboot'
  _BRANCH_NAME: 'main' # or whatever branch you want to use
  _SERVICE_NAME: 'gradlespringboot'
  _VERSION: '0.0.1-SNAPSHOT' # or dynamic versioning

# Timeouts and other options
timeout: '900s'
